# Generated by Django 5.2.15 on 2026-06-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_pi_tracker', '0002_piproject_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piproject',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='piowner',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
