# Generated by Django 5.2.15 on 2026-06-09 12:41

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0003_alter_piproject_options_piowner_last_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="piextractorpin",
            name="head_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="piplanet",
            name="constellation_name",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="piplanet",
            name="region_name",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="piplanet",
            name="security_status",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="piplanet",
            name="solar_system_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="piplanet",
            name="solar_system_name",
            field=models.CharField(default="", max_length=64),
        ),
    ]
