# Generated by Django 5.2.15 on 2026-06-09 13:12

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0004_piextractorpin_head_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PiMarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField(unique=True)),
                ("type_name", models.CharField(max_length=100)),
                ("tier", models.IntegerField(default=0)),
                ("jita_buy", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tier", "type_name"],
            },
        ),
    ]
