# Generated by Django 5.2.15 on 2026-06-09 13:56

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0005_pimarketprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PiStorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField()),
                ("type_name", models.CharField(max_length=100)),
                ("amount", models.BigIntegerField(default=0)),
                (
                    "planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_items",
                        to="aa_pi_tracker.piplanet",
                    ),
                ),
            ],
            options={
                "ordering": ["type_name"],
                "unique_together": {("planet", "type_id")},
            },
        ),
    ]
