# Generated by Django 5.2.15 on 2026-06-10 07:09

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0008_piplanet_user_resource"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piprojectplanet",
            options={"ordering": ["role", "planet__planet_name"]},
        ),
        migrations.AddField(
            model_name="piprojectplanet",
            name="assigned_p0",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="piprojectplanet",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("miner", "Miner"),
                    ("factory", "Factory"),
                    ("factory_p4", "P4 Factory"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
