# Generated by Django 5.2.15 on 2026-06-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_pi_tracker', '0009_piprojectplanet_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piprojectplanet',
            options={'ordering': ['role', 'planet__planet_name', 'planned_char_name']},
        ),
        migrations.AlterUniqueTogether(
            name='piprojectplanet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='piprojectplanet',
            name='planned_char_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piprojectplanet',
            name='planned_char_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='piprojectplanet',
            name='planned_planet_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='piprojectplanet',
            name='planned_system_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='piprojectplanet',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_links', to='aa_pi_tracker.piplanet'),
        ),
    ]
