# Generated by Django 5.2.15 on 2026-06-10 17:07

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0010_piprojectplanet_planned"),
    ]

    operations = [
        migrations.AddField(
            model_name="piowner",
            name="advanced_planetology",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="piowner",
            name="planetology",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="piowner",
            name="remote_sensing",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
