# Generated by Django 5.2.15 on 2026-06-10 22:57

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0014_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piusersettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
