# Generated by Django 5.2.15 on 2026-06-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_pi_tracker', '0015_alter_piusersettings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piprojectobjective',
            name='target_qty_per_hour',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
