# Generated by Django 5.2.15 on 2026-06-11 15:05

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0016_alter_piprojectobjective_target_qty_per_hour"),
    ]

    operations = [
        migrations.CreateModel(
            name="PiMaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.IntegerField()),
                ("date", models.DateField()),
                ("step", models.PositiveSmallIntegerField(default=1)),
                ("done", models.BooleanField(default=False)),
                ("planet_checks", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="aa_pi_tracker.piproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "default_permissions": (),
                "unique_together": {("project", "character_id", "date")},
            },
        ),
    ]
