# Generated by Django 5.2.15 on 2026-06-13 21:24

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0017_maintenance_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pimaintenancelog",
            name="character_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="pimarketprice",
            name="jita_buy",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="piplanet",
            name="planet_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="piplanet",
            name="solar_system_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piproject",
            name="corp_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piprojectplanet",
            name="planned_char_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piusersettings",
            name="home_system_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
