# Generated by Django 5.2.15 on 2026-06-13 22:50

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0018_alter_pimaintenancelog_character_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piextractorpin",
            options={"default_permissions": (), "ordering": ["planet", "product_name"]},
        ),
        migrations.AlterModelOptions(
            name="pifactorypin",
            options={
                "default_permissions": (),
                "ordering": ["planet", "schematic_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="pimarketprice",
            options={"default_permissions": (), "ordering": ["tier", "type_name"]},
        ),
        migrations.AlterModelOptions(
            name="piowner",
            options={
                "default_permissions": (),
                "ordering": ["character__character_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="piplanet",
            options={
                "default_permissions": (),
                "ordering": ["owner__character__character_name", "planet_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="piproject",
            options={"default_permissions": (), "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="piprojectobjective",
            options={"default_permissions": (), "ordering": ["schematic_name"]},
        ),
        migrations.AlterModelOptions(
            name="piprojectplanet",
            options={
                "default_permissions": (),
                "ordering": ["role", "planet__planet_name", "planned_char_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="pistorageitem",
            options={"default_permissions": (), "ordering": ["type_name"]},
        ),
        migrations.AddField(
            model_name="piextractorpin",
            name="notified_expiry",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="piextractorpin",
            name="product_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="pifactorypin",
            name="schematic_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="piplanet",
            name="constellation_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="piplanet",
            name="planet_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="piplanet",
            name="region_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="piplanet",
            name="solar_system_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
