# Generated by Django 5.2.15 on 2026-06-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aa_pi_tracker", "0019_alter_piextractorpin_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piplanet",
            options={"default_permissions": (), "ordering": ["planet_name"]},
        ),
    ]
